export type Ingredient = {
  slug: string;
  name: string;
  sanskritName?: string;
  tagline: string;
  description: string;
  benefits: string[];
  usedIn: string[];
  category: 'herb' | 'oil' | 'mineral' | 'botanical';
  origin: string;
};

export const INGREDIENTS: Ingredient[] = [
  {
    slug: 'kumkumadi',
    name: 'Kumkumadi',
    sanskritName: 'Kumkumadi Tailam',
    tagline: 'The golden elixir of Ayurvedic skin brightening.',
    description:
      'Kumkumadi Tailam is a classical Ayurvedic oil blend anchored by saffron (Crocus sativus), renowned for over a thousand years as a complexion enhancer. Its potent antioxidant profile — including safranal and crocin — neutralises free radicals generated by UV exposure and post-exercise oxidative stress. The oil deeply nourishes skin cells, reduces melanin over-production triggered by sun and heat, and imparts a visible luminosity to dull, active skin.',
    benefits: [
      'Brightens uneven skin tone caused by sun exposure and post-inflammatory hyperpigmentation',
      'Reduces oxidative stress on skin after intense outdoor activity',
      'Boosts collagen synthesis for improved skin elasticity and recovery',
      'Calms inflammation and soothes redness from sweat and friction',
      'Deeply moisturises without clogging pores during high-movement routines',
    ],
    usedIn: ['thavare-body-lotion'],
    category: 'oil',
    origin: 'Kashmir Valley, India',
  },
  {
    slug: 'ashwagandha',
    name: 'Ashwagandha',
    sanskritName: 'Withania somnifera',
    tagline: 'The adaptogen that brings calm to stressed, active skin.',
    description:
      'Ashwagandha, classified as a Rasayana in Ayurveda, is prized for its ability to reduce cortisol-driven inflammation — both internally and topically. Applied to skin, its withanolide compounds suppress stress-induced degradation of the skin barrier, helping active skin recover faster from the cumulative insults of sweat, friction, and environmental exposure. It supports the skin\'s natural regenerative cycle, particularly during the recovery window after sport or exercise.',
    benefits: [
      'Reduces cortisol-driven skin inflammation triggered by physical and thermal stress',
      'Strengthens the skin barrier against sweat, friction, and environmental pollutants',
      'Accelerates post-exercise skin recovery and reduces soreness-related sensitivity',
      'Improves skin texture and suppleness through adaptogenic action',
      'Supports collagen integrity for long-term resilience in active skin',
    ],
    usedIn: ['thavare-body-lotion', 'thavare-body-wash'],
    category: 'herb',
    origin: 'Madhya Pradesh & Rajasthan, India',
  },
  {
    slug: 'neem',
    name: 'Neem',
    sanskritName: 'Azadirachta indica',
    tagline: 'Nature\'s most powerful antibacterial shield for active skin.',
    description:
      'Neem has been a cornerstone of Ayurvedic medicine for millennia, valued for its potent antibacterial, antifungal, and anti-inflammatory properties. For active and sport-oriented skin, neem\'s nimbidin and azadirachtin compounds directly combat the bacterial overgrowth that causes sweat-induced breakouts, body acne, and folliculitis. Its bitter compounds also regulate excess sebum production, keeping skin clear and balanced even through prolonged physical activity.',
    benefits: [
      'Eliminates sweat-induced bacteria that cause body acne and folliculitis',
      'Regulates sebum production to keep skin balanced during high-intensity activity',
      'Reduces post-workout skin inflammation and redness',
      'Soothes chafing, rashes, and friction-related skin irritation',
      'Antifungal action prevents humid-environment skin infections',
    ],
    usedIn: ['thavare-body-wash'],
    category: 'botanical',
    origin: 'Tamil Nadu & Andhra Pradesh, India',
  },
  {
    slug: 'turmeric',
    name: 'Turmeric',
    sanskritName: 'Curcuma longa',
    tagline: 'Ayurveda\'s golden anti-inflammatory, reborn for active skin.',
    description:
      'Turmeric\'s active compound, curcumin, is one of the most studied natural anti-inflammatories in modern dermatology. In Ayurveda it has been used for centuries to reduce Pitta-aggravated redness, swelling, and skin irritation — conditions directly mirrored by post-workout inflammation. Topically applied, curcumin inhibits NF-κB pathways to calm skin redness and swelling, while its antioxidant power neutralises the reactive oxygen species (ROS) generated by prolonged UV and heat exposure during outdoor activity.',
    benefits: [
      'Calms post-workout skin redness and visible inflammation rapidly',
      'Neutralises free radicals from UV exposure during outdoor sport',
      'Fades post-inflammatory hyperpigmentation and dark spots over time',
      'Supports wound healing for minor abrasions and friction burns',
      'Balances Pitta-dominant skin conditions aggravated by heat and sweat',
    ],
    usedIn: ['thavare-body-lotion', 'thavare-sun-screen', 'thavare-body-wash'],
    category: 'herb',
    origin: 'Kerala & Karnataka, India',
  },
  {
    slug: 'aloe-vera',
    name: 'Aloe Vera',
    sanskritName: 'Kumari',
    tagline: 'Instant cooling hydration for sun-kissed and heat-stressed skin.',
    description:
      'Known in Ayurveda as Kumari — meaning "the eternally young" — aloe vera gel is a polysaccharide-rich matrix that delivers immediate, deep hydration to compromised skin. For active skin exposed to sun and wind, its acemannan compounds act as humectants, locking in moisture lost through sweat and evaporation. Aloe\'s natural salicylates provide gentle anti-inflammatory action, while its cooling thermal effect directly counteracts the heat retention that causes discomfort and redness in sun-exposed or post-exercise skin.',
    benefits: [
      'Provides immediate cooling relief to sun-exposed and heat-stressed skin',
      'Restores skin hydration lost through prolonged sweating and outdoor exposure',
      'Accelerates healing of minor sunburn, abrasions, and friction sores',
      'Soothes razor burn and irritation from grooming around sporting activity',
      'Lightweight, non-greasy hydration that does not impede movement or breathability',
    ],
    usedIn: ['thavare-sun-screen', 'thavare-adolescent-sun-block', 'thavare-body-lotion'],
    category: 'botanical',
    origin: 'Rajasthan & Gujarat, India',
  },
  {
    slug: 'vetiver',
    name: 'Vetiver',
    sanskritName: 'Khus (Chrysopogon zizanioides)',
    tagline: 'The cooling grass root that tames heat, sweat, and body odour.',
    description:
      'Vetiver root oil — derived from the deep root system of khus grass — is classified as a Sheeta (cooling) herb in Ayurveda, prescribed specifically for Pitta-aggravated heat conditions. Its terpenoid-rich essential oil regulates excess body heat at the skin surface, reducing the thermal discomfort and excessive sweating associated with intense physical activity. Vetiver\'s natural deodorising compounds neutralise body odour at the source by inhibiting the odour-producing bacteria that thrive in warm, humid skin conditions.',
    benefits: [
      'Regulates excess body heat and surface skin temperature during activity',
      'Neutralises odour-causing bacteria for long-lasting natural freshness',
      'Reduces excessive perspiration without blocking the body\'s natural cooling system',
      'Calms skin hypersensitivity triggered by heat, humidity, and friction',
      'Grounding and calming effect that supports mental recovery post-sport',
    ],
    usedIn: ['thavare-body-wash', 'thavare-body-lotion'],
    category: 'oil',
    origin: 'Tamil Nadu & Kerala, India',
  },
  {
    slug: 'sandalwood',
    name: 'Sandalwood',
    sanskritName: 'Chandan (Santalum album)',
    tagline: 'Ancient skin soother that heals friction, heat, and irritation.',
    description:
      'Sandalwood\'s active compound alpha-santalol has clinically demonstrated anti-inflammatory and skin-barrier repair properties, making it among the most relevant Ayurvedic actives for sport-related skin stress. In Ayurvedic tradition, sandalwood paste has been applied for generations to cool inflamed skin, soothe rashes, and reduce friction-related skin breakdown. For active skin, its ability to reduce transepidermal water loss (TEWL) and calm sensory nerve endings makes it ideal for managing the irritation, heat rash, and chafing that arise during sustained physical activity.',
    benefits: [
      'Soothes chafing, heat rash, and friction-induced skin breakdown',
      'Reduces transepidermal water loss to keep skin supple through extended activity',
      'Calms sensory nerve irritation from tight sportswear and repetitive movement',
      'Anti-inflammatory action reduces visible redness and localised skin swelling',
      'Imparts a gentle, non-synthetic fragrance that is naturally deodorising',
    ],
    usedIn: ['thavare-body-lotion', 'thavare-body-wash'],
    category: 'oil',
    origin: 'Mysuru, Karnataka, India',
  },
  {
    slug: 'manjistha',
    name: 'Manjistha',
    sanskritName: 'Rubia cordifolia',
    tagline: 'Ayurveda\'s premier blood-purifier for pigmentation and dark spots.',
    description:
      'Manjistha is one of the most valued Rakta-shodhaka (blood-purifying) herbs in classical Ayurveda, traditionally prescribed to address hyperpigmentation, uneven skin tone, and chronic inflammatory skin conditions. Its active constituents — purpurin, munjistin, and xanthopurpurin — inhibit melanin synthesis and accelerate the clearance of post-inflammatory pigmentation, including the dark spots and uneven patches that active individuals develop through repeated sun exposure and post-exercise inflammation. Manjistha also supports lymphatic drainage, reducing the puffiness and dullness associated with physical fatigue.',
    benefits: [
      'Fades post-sport dark spots and hyperpigmentation from repeated sun and heat exposure',
      'Inhibits excess melanin synthesis triggered by UV and inflammation',
      'Purifies skin at a cellular level by supporting lymphatic circulation',
      'Reduces dullness and fatigue-related skin congestion after intense training',
      'Long-term evening of skin tone for active individuals prone to uneven pigmentation',
    ],
    usedIn: ['thavare-body-lotion', 'thavare-sun-screen'],
    category: 'herb',
    origin: 'Western Ghats & Himalayan Foothills, India',
  },
];
