#!/bin/bash
SHOP="thavare-2.myshopify.com"
TOKEN="${SHOPIFY_ADMIN_TOKEN:?Set SHOPIFY_ADMIN_TOKEN env var before running}"
API="https://${SHOP}/admin/api/2024-01/products.json"

echo "=== Creating Body Wash ==="
curl -s -X POST "$API" -H "Content-Type: application/json" -H "X-Shopify-Access-Token: $TOKEN" -d '{"product":{"title":"Thavare Body Wash","body_html":"<p>A clinically crafted Ayurvedic body wash designed for the skin that moves. Blue Lotus extract calms and protects, while Wild Himalayan Cherry delivers powerful antioxidants.</p>","vendor":"Thavare","product_type":"Body Wash","tags":["pre-sport","bestseller"],"variants":[{"price":"499.00","sku":"THV-BW-200","inventory_management":"shopify"}],"metafields":[{"namespace":"custom","key":"subtitle","value":"Blue Lotus + Wild Himalayan Cherry","type":"single_line_text_field"},{"namespace":"custom","key":"badge","value":"Bestseller","type":"single_line_text_field"},{"namespace":"custom","key":"category","value":"sport","type":"single_line_text_field"},{"namespace":"custom","key":"category_label","value":"Pre-Sport","type":"single_line_text_field"},{"namespace":"custom","key":"ingredients","value":"Blue Lotus Extract, Wild Himalayan Cherry, Neem Leaf Extract, Aloe Vera, Glycerin","type":"single_line_text_field"},{"namespace":"custom","key":"how_to_use","value":"Apply to wet skin, lather gently, and rinse.","type":"single_line_text_field"}]}}'
echo ""

echo "=== Creating Body Lotion ==="
curl -s -X POST "$API" -H "Content-Type: application/json" -H "X-Shopify-Access-Token: $TOKEN" -d '{"product":{"title":"Thavare Body Lotion","body_html":"<p>Sandalwood has been used in Ayurveda for centuries to calm inflamed skin and restore natural radiance. Paired with Blue Lotus extract, this lotion absorbs quickly to deliver deep hydration.</p>","vendor":"Thavare","product_type":"Body Lotion","tags":["recovery","new"],"variants":[{"price":"599.00","sku":"THV-BL-200","inventory_management":"shopify"}],"metafields":[{"namespace":"custom","key":"subtitle","value":"Blue Lotus + Sandalwood","type":"single_line_text_field"},{"namespace":"custom","key":"badge","value":"New","type":"single_line_text_field"},{"namespace":"custom","key":"category","value":"recovery","type":"single_line_text_field"},{"namespace":"custom","key":"category_label","value":"Recovery","type":"single_line_text_field"},{"namespace":"custom","key":"ingredients","value":"Blue Lotus Extract, Sandalwood Oil, Shea Butter, Squalane, Ashwagandha Root","type":"single_line_text_field"},{"namespace":"custom","key":"how_to_use","value":"Apply generously to clean skin after workout or shower.","type":"single_line_text_field"}]}}'
echo ""

echo "=== Creating Sun Screen ==="
curl -s -X POST "$API" -H "Content-Type: application/json" -H "X-Shopify-Access-Token: $TOKEN" -d '{"product":{"title":"Thavare Sun Screen","body_html":"<p>Most sunscreens were not built for sweating. Ours was. Butter Tree extract forms a breathable protective film that stays on through activity. SPF 30, PA+++, non-comedogenic.</p>","vendor":"Thavare","product_type":"Sunscreen","tags":["sun-care","new"],"variants":[{"price":"699.00","sku":"THV-SS-50","inventory_management":"shopify"}],"metafields":[{"namespace":"custom","key":"subtitle","value":"Blue Lotus + Butter Tree - SPF 30","type":"single_line_text_field"},{"namespace":"custom","key":"badge","value":"New","type":"single_line_text_field"},{"namespace":"custom","key":"category","value":"sun-protection","type":"single_line_text_field"},{"namespace":"custom","key":"category_label","value":"Sun Care","type":"single_line_text_field"},{"namespace":"custom","key":"ingredients","value":"Butter Tree Extract, Blue Lotus Extract, Zinc Oxide, Titanium Dioxide, Green Tea","type":"single_line_text_field"},{"namespace":"custom","key":"how_to_use","value":"Apply liberally 15 minutes before sun exposure. Reapply every 2 hours.","type":"single_line_text_field"}]}}'
echo ""

echo "=== Creating Adolescent Sun Block ==="
curl -s -X POST "$API" -H "Content-Type: application/json" -H "X-Shopify-Access-Token: $TOKEN" -d '{"product":{"title":"Thavare Adolescent Sun Block","body_html":"<p>Willow Bark is nature s salicylic acid - it keeps pores clear while Sandalwood calms post-sport redness. A mineral-first formula for young skin. SPF 30.</p>","vendor":"Thavare","product_type":"Sunscreen","tags":["sun-care","new","adolescent"],"variants":[{"price":"549.00","sku":"THV-ASB-50","inventory_management":"shopify"}],"metafields":[{"namespace":"custom","key":"subtitle","value":"Sandalwood + Willow Bark - SPF 30","type":"single_line_text_field"},{"namespace":"custom","key":"badge","value":"New","type":"single_line_text_field"},{"namespace":"custom","key":"category","value":"sun-protection","type":"single_line_text_field"},{"namespace":"custom","key":"category_label","value":"Sun Care","type":"single_line_text_field"},{"namespace":"custom","key":"ingredients","value":"Sandalwood Extract, Willow Bark Extract, Zinc Oxide, Aloe Vera, Vitamin E","type":"single_line_text_field"},{"namespace":"custom","key":"how_to_use","value":"Apply to face and exposed skin before going outdoors. Suitable for ages 10+.","type":"single_line_text_field"}]}}'
echo ""

echo "=== Creating Kumkumadi Taila ==="
curl -s -X POST "$API" -H "Content-Type: application/json" -H "X-Shopify-Access-Token: $TOKEN" -d '{"product":{"title":"Thavare Kumkumadi Taila","body_html":"<p>One of Ayurveda s oldest formulations. Cold-pressed and processed with milk, this golden oil works overnight to fade hyperpigmentation, restore glow, and nourish skin that trains hard.</p>","vendor":"Thavare","product_type":"Face Oil","tags":["teal-ayurveda","signature"],"variants":[{"price":"899.00","sku":"THV-KT-15","inventory_management":"shopify"}],"metafields":[{"namespace":"custom","key":"subtitle","value":"Cold-pressed Oil - Processed with Milk","type":"single_line_text_field"},{"namespace":"custom","key":"badge","value":"Signature","type":"single_line_text_field"},{"namespace":"custom","key":"category","value":"daily-essentials","type":"single_line_text_field"},{"namespace":"custom","key":"category_label","value":"Teal Ayurveda","type":"single_line_text_field"},{"namespace":"custom","key":"ingredients","value":"Saffron, Sandalwood, Lotus, Vetiver, Licorice, Sesame Base Oil","type":"single_line_text_field"},{"namespace":"custom","key":"how_to_use","value":"Apply 3-4 drops to clean face at night. Massage gently. Leave overnight.","type":"single_line_text_field"}]}}'
echo ""

echo "=== Creating Anti Perspirant Lotion ==="
curl -s -X POST "$API" -H "Content-Type: application/json" -H "X-Shopify-Access-Token: $TOKEN" -d '{"product":{"title":"Thavare Anti Perspirant Lotion","body_html":"<p>A natural Ayurvedic anti-perspirant that controls sweat without blocking pores. Vetiver and Camphor cool the skin and reduce perspiration while Aloe Vera keeps skin soft.</p>","vendor":"Thavare","product_type":"Body Lotion","tags":["sport","anti-perspirant"],"variants":[{"price":"549.00","sku":"THV-APL-100","inventory_management":"shopify"}],"metafields":[{"namespace":"custom","key":"subtitle","value":"Vetiver + Camphor","type":"single_line_text_field"},{"namespace":"custom","key":"category","value":"sport","type":"single_line_text_field"},{"namespace":"custom","key":"category_label","value":"Sport","type":"single_line_text_field"},{"namespace":"custom","key":"ingredients","value":"Vetiver Extract, Camphor, Aloe Vera, Neem Oil, Witch Hazel","type":"single_line_text_field"},{"namespace":"custom","key":"how_to_use","value":"Apply to clean, dry skin on high-sweat areas before activity.","type":"single_line_text_field"}]}}'
echo ""

echo "=== All products created ==="
